# Generated by Django 5.1.5 on 2025-01-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_san_pham', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_san_pham', models.CharField(max_length=100)),
                ('gia_ban', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ton_kho', models.IntegerField()),
            ],
        ),
    ]
