# Generated by Django 5.1.5 on 2025-01-30 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hoa_don', models.CharField(max_length=100)),
                ('ngay_lap', models.DateTimeField()),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhan_vien', models.CharField(max_length=100)),
                ('chuc_vu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuayBanHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_quay', models.CharField(max_length=100)),
                ('vi_tri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san_pham', models.CharField(max_length=100)),
                ('so_luong', models.IntegerField()),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hoadon')),
            ],
        ),
    ]
