# Generated by Django 5.1.5 on 2025-01-30 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlybanhang', '0003_uudaikhachhang'),
        ('home', '0002_hoadon_nhanvien_quaybanhang_chitiethoadon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_san_pham', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_san_pham', models.CharField(max_length=255)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('ma_khuyen_mai', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phan_tram_chiet_khau', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='TichDiem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('so_diem', models.IntegerField(default=0)),
                ('ma_khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlybanhang.khachhang')),
            ],
        ),
    ]
