# Generated by Django 5.1.5 on 2025-01-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sanpham_khuyenmai_tichdiem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TichDiem',
        ),
    ]
