# Generated by Django 5.1.4 on 2025-01-14 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiaVang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thoi_gian', models.DateTimeField()),
                ('gia_vang_24k', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('ma_hoa_don', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_lap', models.DateTimeField()),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ma_khach_hang', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_khach_hang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('ma_loai_san_pham', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_loai_san_pham', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nhan_vien', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuayBanHang',
            fields=[
                ('ma_quay', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_quay', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_san_pham', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_san_pham', models.CharField(max_length=100)),
                ('gia_ban', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ton_kho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MuaLai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_mua_lai', models.DateTimeField()),
                ('gia_mua_lai', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlybanhang.hoadon')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlybanhang.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('ma_khuyen_mai', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phan_tram_chiet_khau', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlybanhang.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ma_hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlybanhang.hoadon')),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlybanhang.sanpham')),
            ],
        ),
    ]
