# Generated by Django 5.1.5 on 2025-01-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlybanhang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='quay_lam_viec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_vien_quay_lam_viec', to='Quanlybanhang.quaybanhang'),
        ),
        migrations.AddField(
            model_name='quaybanhang',
            name='nhan_vien_phu_trach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quanlybanhang.nhanvien'),
        ),
        migrations.AddField(
            model_name='quaybanhang',
            name='san_phams',
            field=models.ManyToManyField(related_name='quays', to='Quanlybanhang.sanpham'),
        ),
    ]
