# Generated by Django 5.1.5 on 2025-01-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlybanhang', '0004_alter_sanpham_ma_san_pham_alter_sanpham_ten_san_pham'),
    ]

    operations = [
        migrations.CreateModel(
            name='TichDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_diem', models.IntegerField()),
                ('thoi_gian_tich_diem', models.DateTimeField(auto_now_add=True)),
                ('ma_khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlybanhang.khachhang')),
            ],
        ),
    ]
